version: '3.3'
services:
  python-backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
    - .:/app

  react-frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
    - .:/front/app
    depends_on:
    - python-backend
